version: "3"

silent: true

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all

  build:examples:
    desc: "Build examples"
    cmds:
      - GOOS=wasip1 GOARCH=wasm go1.24rc1 build -buildmode=c-shared -o examples/plugins/hello/main.wasm examples/plugins/hello/main.go
